language: ruby
before_install:
  - gem install bundler -v '1.17.3'
bundler_args: --without dev
rvm:
  - 2.1.9
  - 2.2.9
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - jruby-9.0.5.0
  - jruby-9.1.2.0
matrix:
  allow_failures:
    # rbx no longer builds on travis
    - rvm: rbx-2.4.1
    - rvm: rbx-2.5.8
    - rvm: 2.2.10
  fast_finish: true
