language: ruby
before_install:
  - gem update --system
  - gem install bundler
bundler_args: --without dev
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - jruby-1.6
  - jruby-1.7.25
  - jruby-9
  - rbx-2.4.1
  - rbx-2.5.8
  - rbx-head
matrix:
  allow_failures:
    # rbx 2.4 no longer builds on travis
    - rvm: rbx-2.4.1
  fast_finish: true
