language: ruby
before_install:
  - gem update --system
  - gem install bundler
bundler_args: --without dev
rvm:
  - ruby-head
  - 2.3.1
  - 2.2.0
  - 2.1.5
  - 2.0.0
  - 1.9.3
  - jruby-1.7.9
  - rbx-2.4.1
  - rbx-2.5.8
matrix:
  allow_failures:
    # rbx no longer builds on travis
    - rvm: rbx-2.4.1
    - rvm: rbx-2.5.8
  fast_finish: true
